BEGIN;


TRUNCATE COLUMNHISTORIES, TASKHISTORIES, TASKS, COLUMNS,
        BOARDS, USERROLES, USERS, PROJECTS
        RESTART IDENTITY CASCADE;


INSERT INTO roles(roleid, title, permissions) VALUES
    (1, 'Administrator', 31)           -- уже есть в миграциях, добавится только при необходимости
ON CONFLICT (roleid) DO NOTHING;

INSERT INTO roles(roleid, title, permissions) VALUES
    (2, 'Project Manager', 31),
    (3, 'Developer', 3),
    (4, 'Viewer', 0)
ON CONFLICT (roleid) DO NOTHING;

INSERT INTO statuses(statusid, title, color) VALUES
    (1, 'Todo',        '#ffffff'),
    (2, 'In-Progress', '#00aa00'),
    (3, 'Complete',    '#ff0000')
ON CONFLICT (statusid) DO NOTHING;

INSERT INTO priorities(priorityid, title) VALUES
    (1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low')
ON CONFLICT (priorityid) DO NOTHING;

INSERT INTO severities(severityid, title) VALUES
    (1, 'Blocker'), (2, 'Major'), (3, 'Minor'), (4, 'Trivial')
ON CONFLICT (severityid) DO NOTHING;


INSERT INTO users(username, login, password)
SELECT *
FROM  (VALUES
  ('Alice Johnson',  'alice',  'pass'),
  ('Bob Smith',      'bob',    'pass'),
  ('Carlos Méndez',  'carlos', 'pass'),
  ('Diana Chen',     'diana',  'pass'),
  ('Evan Brown',     'evan',   'pass')
) AS u(username, login, password);


WITH p AS (
  INSERT INTO projects(title, description, startdate, enddate, userid)
       VALUES ('Sample project for metrics',
               'Autogenerated test data',
               NOW() - INTERVAL '30 days',
               NOW() + INTERVAL '60 days',
               1)              -- owner = Alice
       RETURNING projectid
)

INSERT INTO userroles (userid, roleid, projectid)
SELECT *
FROM (
  SELECT u.userid,
         CASE WHEN u.userid = 1 THEN 2          -- Alice = PM
              ELSE 3                            -- остальные = Dev
         END               AS roleid,
         p.projectid       AS projectid
  FROM users u, p
) AS t;


WITH boards AS (
  INSERT INTO boards(title, description, startdate, enddate, projectid)
  SELECT title, 'Autogenerated board', NOW() - INTERVAL '30 days',
         NOW() + INTERVAL '30 days', p.projectid
  FROM p,
       (VALUES ('Frontend'), ('Backend'), ('QA')) AS b(title)
  RETURNING boardid
), cols AS (
  INSERT INTO columns(title, color, boardid)
  SELECT c.title, c.color, b.boardid
  FROM boards b,
       (VALUES ('Todo',        '#ffffff'),
              ('In Progress', '#00aa00'),
              ('Review',      '#0000ff'),
              ('Done',        '#ff0000')) AS c(title, color)
  RETURNING columnid, title, boardid
)
SELECT 1;


DO
$$
DECLARE
    b  RECORD;
    todo_col  INTEGER;
    prog_col  INTEGER;
    rev_col   INTEGER;
    done_col  INTEGER;
    usr  RECORD;
    prio INTEGER;
    created_at  TIMESTAMP;
    t_id INTEGER;
BEGIN
  -- цикл по доскам
  FOR b IN SELECT boardid FROM boards LOOP
        -- получаем ID колонок для этой доски
        SELECT columnid INTO todo_col  FROM columns WHERE boardid = b.boardid AND title = 'Todo';
        SELECT columnid INTO prog_col  FROM columns WHERE boardid = b.boardid AND title = 'In Progress';
        SELECT columnid INTO rev_col   FROM columns WHERE boardid = b.boardid AND title = 'Review';
        SELECT columnid INTO done_col  FROM columns WHERE boardid = b.boardid AND title = 'Done';

        -- 100 задач
        FOR i IN 1..100 LOOP
            -- случайный исполнитель
            SELECT userid, userroleid
              INTO usr
              FROM users u
              JOIN userroles ur USING (userid)
              WHERE ur.projectid = (SELECT projectid FROM projects LIMIT 1)
              ORDER BY random()
              LIMIT 1;

            prio := (SELECT priorityid FROM priorities ORDER BY random() LIMIT 1);
            created_at := (NOW() - INTERVAL '29 days') + (random() * INTERVAL '14 days');

            INSERT INTO tasks(title, description, datecreated, dateupdated, deadline,
                              columnid, statusid, priorityid, userid, userroleid,
                              backlogid, isepic)
            VALUES (format('Task %s-%s', b.boardid, i),
                    'Generated task',
                    created_at,
                    created_at,
                    created_at + INTERVAL '21 days',
                    todo_col,             -- сначала в Todo
                    1,                    -- статус Todo
                    prio,
                    usr.userid,
                    usr.userroleid,
                    NULL,
                    false)
            RETURNING taskid INTO t_id;

           
            PERFORM pg_sleep(0);  -- микро-пауза, чтобы taskid изменился

           
            INSERT INTO columnhistories(taskid, oldcolumnid, newcolumnid, changedate)
                 VALUES (t_id, todo_col, prog_col, created_at + INTERVAL '2 days');
            INSERT INTO taskhistories (taskid, oldstatus, newstatus, changedate)
                 VALUES (t_id, 'Todo', 'In-Progress', created_at + INTERVAL '2 days');

           
            UPDATE tasks
               SET columnid = prog_col,
                   statusid = 2,
                   dateupdated = created_at + INTERVAL '2 days'
             WHERE taskid = t_id;

            INSERT INTO columnhistories(taskid, oldcolumnid, newcolumnid, changedate)
                 VALUES (t_id, prog_col, rev_col, created_at + INTERVAL '5 days');
            INSERT INTO taskhistories (taskid, oldstatus, newstatus, changedate)
                 VALUES (t_id, 'In-Progress', 'In-Progress', created_at + INTERVAL '5 days'); 

            
            UPDATE tasks
               SET columnid = rev_col,
                   statusid = 2,
                   dateupdated = created_at + INTERVAL '5 days'
             WHERE taskid = t_id;

            INSERT INTO columnhistories(taskid, oldcolumnid, newcolumnid, changedate)
                 VALUES (t_id, rev_col, done_col, created_at + INTERVAL '7 days');
            INSERT INTO taskhistories (taskid, oldstatus, newstatus, changedate)
                 VALUES (t_id, 'In-Progress', 'Complete', created_at + INTERVAL '7 days');

            UPDATE tasks
               SET columnid = done_col,
                   statusid = 3,
                   dateupdated = created_at + INTERVAL '7 days'
             WHERE taskid = t_id;
        END LOOP;
  END LOOP;
END
$$ LANGUAGE plpgsql;

COMMIT;